// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQZ8fUzlZrumhao0HKt_Rx1Ntfp5c7Bmo',
    appId: '1:882588890018:web:ed3c4fd5951a9450c3f8fb',
    messagingSenderId: '882588890018',
    projectId: 'kopitan-app',
    authDomain: 'kopitan-app.firebaseapp.com',
    storageBucket: 'kopitan-app.firebasestorage.app',
    measurementId: 'G-LH9SS8BL81',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKTmd7uFVPfRsrD3Vf6QXQMlq5haQ4k1c',
    appId: '1:882588890018:android:159af4cb19450605c3f8fb',
    messagingSenderId: '882588890018',
    projectId: 'kopitan-app',
    storageBucket: 'kopitan-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJBHCuUS4P64zUdpjeR4do1xkBDJ8aqtg',
    appId: '1:882588890018:ios:5368ccb4f6537d9fc3f8fb',
    messagingSenderId: '882588890018',
    projectId: 'kopitan-app',
    storageBucket: 'kopitan-app.firebasestorage.app',
    iosBundleId: 'com.example.kopitanApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJBHCuUS4P64zUdpjeR4do1xkBDJ8aqtg',
    appId: '1:882588890018:ios:5368ccb4f6537d9fc3f8fb',
    messagingSenderId: '882588890018',
    projectId: 'kopitan-app',
    storageBucket: 'kopitan-app.firebasestorage.app',
    iosBundleId: 'com.example.kopitanApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQZ8fUzlZrumhao0HKt_Rx1Ntfp5c7Bmo',
    appId: '1:882588890018:web:f61d2d1b830eb92bc3f8fb',
    messagingSenderId: '882588890018',
    projectId: 'kopitan-app',
    authDomain: 'kopitan-app.firebaseapp.com',
    storageBucket: 'kopitan-app.firebasestorage.app',
    measurementId: 'G-CJT1DQX1CS',
  );
}
