// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart';
// ...
/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart

/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6X6Qu9NxlqMHLExhMOgxzqCY7PDwu7gg',
    appId: '1:523126020762:web:31c435cee228c023551d23',
    messagingSenderId: '523126020762',
    projectId: 'kopitan-e0633',
    authDomain: 'kopitan-e0633.firebaseapp.com',
    storageBucket: 'kopitan-e0633.firebasestorage.app',
    measurementId: 'G-FZ4LSFGN5X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9hzcOyEy8LUy5XS1Xh3aMwvtI6XqV2Vo',
    appId: '1:523126020762:android:0b93830c4c2078d3551d23',
    messagingSenderId: '523126020762',
    projectId: 'kopitan-e0633',
    storageBucket: 'kopitan-e0633.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDg1ZfOoXf9sKd4PyJsRWXOpC4hmms6W1g',
    appId: '1:523126020762:ios:bced4a768ee24aef551d23',
    messagingSenderId: '523126020762',
    projectId: 'kopitan-e0633',
    storageBucket: 'kopitan-e0633.firebasestorage.app',
    iosBundleId: 'com.example.kopitanApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDg1ZfOoXf9sKd4PyJsRWXOpC4hmms6W1g',
    appId: '1:523126020762:ios:bced4a768ee24aef551d23',
    messagingSenderId: '523126020762',
    projectId: 'kopitan-e0633',
    storageBucket: 'kopitan-e0633.firebasestorage.app',
    iosBundleId: 'com.example.kopitanApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6X6Qu9NxlqMHLExhMOgxzqCY7PDwu7gg',
    appId: '1:523126020762:web:82d947ef88851de1551d23',
    messagingSenderId: '523126020762',
    projectId: 'kopitan-e0633',
    authDomain: 'kopitan-e0633.firebaseapp.com',
    storageBucket: 'kopitan-e0633.firebasestorage.app',
    measurementId: 'G-Z8JJJ2XGB5',
  );
}
